---
title: "DistractMe"
output: html_document
---


# About
It's the 12th December and I'm in need of a distraction to stop me from continuously reading through Twitter and election news. 


From the TidyTuesday project



```{r}
library(tidyverse)



jobs_gender <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-03-05/jobs_gender.csv")
earnings_female <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-03-05/earnings_female.csv") 
employed_gender <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-03-05/employed_gender.csv") 

```


Lets visualise proportion first because we might be able to get some nice gganimate stuff going on:


```{r}

employed_gender %>%
  gather(key = category, value = employed, - year) %>% 
  mutate(gender = case_when(str_detect(category, "female") ~ "female",
                            str_detect(category, "male") ~ "male",
                            str_detect(category, "total") ~ "total"),
         time = case_when(str_detect(category, "full_time") ~ "full time",
                          str_detect(category, "part_time") ~ "part time")) %>% 
  ggplot(aes(x = year, y = employed)) +
  geom_point(aes(shape = time, colour = gender))


```

Kind of annoying that the gender data is of that gender and not of total employment


```{r}

earnings_female %>% 
  ggplot(aes(x = Year, y = percent )) +
  geom_point(aes(colour = group)) +
  labs(y = "Female salary percent of male salary")

```




